version: '3.1'
services:
  mft-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/vodacom/properties/:/data/config/properties/
    ports:
      - "8181:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
