FROM openjdk:11-jre-slim
RUN mkdir -p /app/
RUN mkdir -p /app/logs/
ADD ../target/vodacommft-0.0.1-SNAPSHOT.jar /app/mftservices.jar
ENTRYPOINT ["java", "-Xmx1024m", "-Xms1024m", "-jar", "/app/mftservices.jar"]
