---
mft_namespace: mft
working_dir: /tmp/mft/deployment/kubernetes

#ingress_host: test.ingress.dev.vodacom.co.za
container_replica_amount : 2

container_image_server : hub.docker.com
container_image_version : latest

cpu_max: 50m
memory_max: 128Mi
cpu_requests: 50m
memory_requests: 64Mi
